const projects = [{
    "id": 1,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "AI based Learning Platform",
    "subtitle": "Generative AI and Web Application",
    "duration": "2024-2025",
    "link": "https://www.careerwise.com",
    "topskills": ["React", "TailwindCSS", "Node", "Gemini API"],
    "skills": "HTML, CSS, Tailwind CSS, JavaScript, PHP, MySQL, Payment Gateway, PHPMailer, Team Work.",
    "team": "Team-Size: 6",
    "info": ["The website is designed to provide seamless access to informationabout the latest coding events, hackathons, and workshops.",
      "It also allows students to register for events, track their progress,and view results, all in one place.",
      "My vision is to turn Coders Club into a hub where students can notonly improve their coding skills but also participate in variouschallenges, win exciting rewards, and become a part of a thrivingtech community.",
      "In this Project, I worked as a frontend and backend developer."
    ]
  },
  {
    "id": 2,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "Interactive Doodle Recognizer",
    "subtitle": "Image Processing & Machine Learning",
    "duration": "Dec 2024 - Feb 2025",
    "link": "https://www.doodlerecogniser.in",
    "topskills": ["React", "Node", "Python", "Flask", "CNN"],
    "skills": "Google Doodle, Django, Python, MySQL, Generative AI, PyQT desktop application.",
    "team": "Team-Size: 5",
    "info": ["The website is designed to provide seamless access to informationabout the latest coding events, hackathons, and workshops.",
      "It also allows students to register for events, track their progress,and view results, all in one place.",
      "My vision is to turn Coders Club into a hub where students can notonly improve their coding skills but also participate in variouschallenges, win exciting rewards, and become a part of a thrivingtech community.",
      "In this Project, I worked as a frontend and backend developer."
    ]
  },
  {
    "id": 3,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "Machine Learning Models",
    "subtitle": "Django Web Application and ML",
    "duration": "Mar 2025 - Nov 2025",
    "link": "https://www.mlmodels.redhatcoders.tech",
    "topskills": ["HTML", "CSS", "JavaScript", "EJS", "Node Js"],
    "skills": "React JS, Tailwind CSS, Machine Learning, Deep Learning, Python, Django, MySQL",
    "team": "",
    "info": ["The website is designed to provide seamless access to informationabout the latest coding events, hackathons, and workshops.",
      "It also allows students to register for events, track their progress,and view results, all in one place.",
      "My vision is to turn Coders Club into a hub where students can notonly improve their coding skills but also participate in variouschallenges, win exciting rewards, and become a part of a thrivingtech community.",
      "In this Project, I worked as a frontend and backend developer."
    ]
  },
  {
    "id": 4,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "AI-based Learning Path Generator",
    "subtitle": "Generative AI & Node Js Web Application",
    "duration": "Oct 2024 - Nov 2024",
    "link": "https://www.aicareer.kabeer.in",
    "topskills": ["HTML", "CSS", "JavaScript", "EJS", "Node Js"],
    "skills": "HTML, CSS, JavaScript, EJS, Node Js, Python, LangChain, Generative AI, OpenAI.",
    "team": "",
    "info": ["Personalized Learning Experience: Designed a dynamic web application using Node.js and integrated OpenAI's API to generate tailored learning paths based on user preferences and goals.",
      "User-Centric Design: The website gathers personal inputs, such as interests, career aspirations, and preferred learning pace via radio buttons, to provide a customized and engaging learningjourney.",
      "My Role was to design the Website, integrate the front-end withthe back-end, and display the results generated by the back-end."
    ]
  },
  {
    "id": 5,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "Sprnt Online Business Website",
    "subtitle": "E-Commerce MERN Website",
    "duration": "Jan 2024 - Apr 2025",
    "link": "https://www.sprnt.com",
    "topskills": ["HTML", "CSS", "JavaScript", "EJS", "Node Js"],
    "skills": "HTML, CSS, JavaScript, React JS, MongoDb, Node JS, Express JS, Payment Gateway, Generative AI",
    "team": "Team-Size: 3",
    "info": ["The website is designed to provide seamless access to informationabout the latest coding events, hackathons, and workshops.",
      "It also allows students to register for events, track their progress,and view results, all in one place.",
      "My vision is to turn Coders Club into a hub where students can notonly improve their coding skills but also participate in variouschallenges, win exciting rewards, and become a part of a thrivingtech community.",
      "In this Project, I worked as a frontend and backend developer."
    ]
  },
  {
    "id": 6,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "My Attractive Portfolio",
    "subtitle": "React & PHP Website",
    "duration": "Dec 2024",
    "link": "https://www.kabeer.in",
    "topskills": ["HTML", "CSS", "JavaScript", "EJS", "Node Js"],
    "skills": "HTML, CSS, JavaScript, React JS, PHP, MySQL,",
    "team": "",
    "info": ["The website is designed to provide seamless access to informationabout the latest coding events, hackathons, and workshops.",
      "It also allows students to register for events, track their progress,and view results, all in one place.",
      "My vision is to turn Coders Club into a hub where students can notonly improve their coding skills but also participate in variouschallenges, win exciting rewards, and become a part of a thrivingtech community.",
      "In this Project, I worked as a frontend and backend developer."
    ]
  },
  {
    "id": 7,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "Maglev: Magnetic Levitating Vehicle",
    "subtitle": "Electromagnetic Induction and IOT",
    "duration": "Dec 2024 - Feb 2025",
    "link": "https://maglev.kabeer.in",
    "topskills": ["HTML", "CSS", "JavaScript", "EJS", "Node Js"],
    "skills": "Electromagnetic Induction, Electro Magnets, 3D Printing, Team Work",
    "team": "Team-Size: 6",
    "info": ["The website is designed to provide seamless access to informationabout the latest coding events, hackathons, and workshops.",
      "It also allows students to register for events, track their progress,and view results, all in one place.",
      "My vision is to turn Coders Club into a hub where students can notonly improve their coding skills but also participate in variouschallenges, win exciting rewards, and become a part of a thrivingtech community.",
      "In this Project, I worked as a frontend and backend developer."
    ]
  },
  {
    "id": 8,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "Coders' Club, GPREC Website",
    "subtitle": "Full-Stack Web Application",
    "duration": "Jul 2024 - Aug 2024",
    "link": "https://www.codersclubgprec.in",
    "topskills": ["HTML", "CSS", "JavaScript", "EJS", "Node Js"],
    "skills": "HTML, CSS, Tailwind CSS, JavaScript, PHP, MySQL, Payment Gateway, PHPMailer, Team Work",
    "team": "Team-Size: 3",
    "info": ["The website is designed to provide seamless access to informationabout the latest coding events, hackathons, and workshops.",
      "It also allows students to register for events, track their progress,and view results, all in one place.",
      "My vision is to turn Coders Club into a hub where students can notonly improve their coding skills but also participate in variouschallenges, win exciting rewards, and become a part of a thrivingtech community.",
      "In this Project, I worked as a frontend and backend developer."
    ]
  },
  {
    "id": 9,
    "images": ["college.jpg", "gprec.jpg", "osmania.jpg"],
    "title": "Company Sales Dashboard",
    "subtitle": "Full-Stack Web Application",
    "duration": "Nov 2024",
    "link": "https://www.business.redhatcoders.tech",
    "topskills": ["HTML", "CSS", "JavaScript", "EJS", "Node Js"],
    "skills": "HTML, CSS, JavaScript, JQuery, PHP, MySQL, AJAX, Charts.js",
    "team": "",
    "info": ["Comprehensive Sales Dashboard: Developed a feature-rich webapplication for PrintItOut company to seamlessly manage andvisualize sales, expenses, and profits.",
      "Dynamic Data Management: Enabled easy addition andmodification of transactions, offering real-time insights intofinancial performance with an intuitive and user-friendlyinterface.",
      "Interactive Visualizations: Integrated Charts.js to create dynamicgraphs and detailed reports, helping users easily interpret profit,loss, and expense trends."
    ]
  },

]

export default projects